services:
  - type: web
    name: proyecto-web
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn proyecto.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: proyecto-db
          property: connectionString

databases:
  - name: proyecto-db
    plan: free
